const ACTIONS = {
  ADD_DELIVERY_POINT: 'deliveryRoutes/ADD_DELIVERY_POINT',
  ADD_DELIVERY_ROUTE: 'deliveryRoutes/ADD_DELIVERY_ROUTE',

  COST_CALCULATOR_ADD_POINT: 'costCalculator/COST_CALCULATOR_ADD_POINT',
  COST_CALCULATOR_INSERT_POINT: 'costCalculator/COST_CALCULATOR_INSERT_POINT',
  COST_CALCULATOR_REMOVE_POINT: 'costCalculator/COST_CALCULATOR_REMOVE_POINT',
  COST_CALCULATOR_CHANGE_POINT: 'costCalculator/COST_CALCULATOR_CHANGE_POINT',
} as const;

export default ACTIONS;
